pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "<your-dockerhub-username>/my-app:latest"
    }
    stages {
        stage('Clone Repository') {
            steps {
                checkout([
                    $class: 'GitSCM',
                     branches: [[name: '*/main']], // Specify 'main' branch
                     userRemoteConfigs: [[
                     url: '<your-github-repository-url>',
            ]]
        ])
            }
        }
        stage('Build Application') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Docker Build') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE .'
            }
        }
        stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub_credentials', 
                                        usernameVariable: 'DOCKER_USER', 
                                        passwordVariable: 'DOCKER_PASS')])
                {
                sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    docker push $DOCKER_IMAGE
                   '''
        }
    }
}

        stage('Deploy') {
            steps {
                echo 'Deploy stage placeholder'
            }
        }
    }
}
