pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "<your-dockerhub-username>/proectappforcicd:latest"
    }
    stages {
        stage('Clone Repository') {
            steps {
                checkout([
                    $class: 'GitSCM',
                     branches: [[name: '*/main']], // Specify 'main' branch
                     userRemoteConfigs: [[
                     url: 'https://github.com/amruthakp5/CI-CD-project.git',
            ]]
        ])
            }
        }
        stage('Build Application') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Docker Build') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE .'
            }
        }
        stage('Docker Push') {
            steps {
                sh 'docker login -u <your-dockerhub-username> -p <your-dockerhub-password>'
                sh 'docker push $DOCKER_IMAGE'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy stage placeholder'
            }
        }
    }
}
